<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Songs extends \Entity\Songs implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\Songs' . "\0" . 'id', '' . "\0" . 'Entity\\Songs' . "\0" . 'songName', '' . "\0" . 'Entity\\Songs' . "\0" . 'artistName', '' . "\0" . 'Entity\\Songs' . "\0" . 'songSrc', '' . "\0" . 'Entity\\Songs' . "\0" . 'imageSrc', '' . "\0" . 'Entity\\Songs' . "\0" . 'lyricSrc'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\Songs' . "\0" . 'id', '' . "\0" . 'Entity\\Songs' . "\0" . 'songName', '' . "\0" . 'Entity\\Songs' . "\0" . 'artistName', '' . "\0" . 'Entity\\Songs' . "\0" . 'songSrc', '' . "\0" . 'Entity\\Songs' . "\0" . 'imageSrc', '' . "\0" . 'Entity\\Songs' . "\0" . 'lyricSrc'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Songs $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSongName($songName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSongName', [$songName]);

        return parent::setSongName($songName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSongName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSongName', []);

        return parent::getSongName();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtistName($artistName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtistName', [$artistName]);

        return parent::setArtistName($artistName);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtistName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtistName', []);

        return parent::getArtistName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSongSrc($songSrc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSongSrc', [$songSrc]);

        return parent::setSongSrc($songSrc);
    }

    /**
     * {@inheritDoc}
     */
    public function getSongSrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSongSrc', []);

        return parent::getSongSrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageSrc($imageSrc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageSrc', [$imageSrc]);

        return parent::setImageSrc($imageSrc);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageSrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageSrc', []);

        return parent::getImageSrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setLyricSrc($lyricSrc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLyricSrc', [$lyricSrc]);

        return parent::setLyricSrc($lyricSrc);
    }

    /**
     * {@inheritDoc}
     */
    public function getLyricSrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLyricSrc', []);

        return parent::getLyricSrc();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
